sonar.projectKey=Ashhh02_CITESched
sonar.organization=ashhh02  # Make sure this matches your SonarCloud Org name!
sonar.sources=citesched_flutter/lib,citesched_server/lib
sonar.host.url=https://sonarcloud.io
sonar.dart.analysis.reportPaths=analysis_report.txt