name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: |
          cd citesched_flutter && flutter pub get
          cd ../citesched_server && dart pub get

      - name: Generate Reports
        run: |
          # Generate analysis report for SonarCloud
          cd citesched_flutter && flutter analyze --write=../analysis_report.txt || true
          
          # Generate coverage files (Optional, but fixes the 0.0% coverage)
          cd citesched_flutter && flutter test --coverage || true
          cd ../citesched_server && dart test --coverage=coverage || true
          cd ../citesched_server && dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.dart_tool/package_config.json --report-on=lib || true

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
