name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable # Using 'stable' ensures compatibility with your current project

      - name: Install Dependencies (Server)
        working-directory: citesched_server
        run: dart pub get

      - name: Install Dependencies (Flutter)
        working-directory: citesched_flutter
        run: dart pub get

      - name: Check All Formatting
        # We run this from the root (.) so it checks both folders at once
        run: dart format --set-exit-if-changed .