name: Format

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      # Download rules for the server
      - name: Install Server Dependencies
        working-directory: citesched_server
        run: dart pub get

      # Download rules for the flutter app
      - name: Install Flutter Dependencies
        working-directory: citesched_flutter
        run: dart pub get

      # Now check everything from the root
      - name: Check Formatting
        run: dart format --set-exit-if-changed .